# test no BAM outputting (non-standard GRCh38 scaffolds inside)
singularity run -B /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/ -B /mnt/NVMeScratch/tmp gcparagon_0.6.15.sif --bam /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/input_BAMs/Villanueva_DEBUG/CF24_0064.rh.bam --temporary-directory /mnt/NVMeScratch/tmp --out-dir /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/GCparagon_output_v0.6.15/Villanueva_DEBUG-ubuntu22_conda_env --preset 1 --threads 12 --dont-output-bam --unclipped-min-aln-fraction 0.05
singularity run -B /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/ -B /mnt/NVMeScratch/tmp gcparagon_0.6.15-lenient.sif --bam /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/input_BAMs/Villanueva_DEBUG/CF24_0064.rh.bam --temporary-directory /mnt/NVMeScratch/tmp --out-dir /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/GCparagon_output_v0.6.15/Villanueva_DEBUG-lenient_conda_env --preset 1 --threads 12 --dont-output-bam --unclipped-min-aln-fraction 0.05

# test BAM outputting
singularity run -B /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/ -B /mnt/NVMeScratch/tmp gcparagon_0.6.15.sif --bam /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/input_BAMs/20230530_ALL_B6_3_tf_0.01_cov_5.0.bam --temporary-directory /mnt/NVMeScratch/tmp --out-dir /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/GCparagon_output_v0.6.15/BAM_output-ubuntu22_conda_env --preset 1 --threads 24
singularity run -B /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/ -B /mnt/NVMeScratch/tmp gcparagon_0.6.15-lenient.sif --bam /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/input_BAMs/20230530_ALL_B6_3_tf_0.01_cov_5.0.bam --temporary-directory /mnt/NVMeScratch/tmp --out-dir /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/GCparagon_output_v0.6.15/BAM_output-lenient_conda_env --preset 1 --threads 24

# test same but no BAM outputting and allow more softclip
singularity run -B /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/ -B /mnt/NVMeScratch/tmp gcparagon_0.6.15.sif --bam /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/input_BAMs/20230530_ALL_B6_3_tf_0.01_cov_5.0.bam --temporary-directory /mnt/NVMeScratch/tmp --out-dir /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/GCparagon_output_v0.6.15/noBAM_output_moreSC-ubuntu22_conda_env --preset 1 --threads 24 --dont-output-bam --unclipped-min-aln-fraction 0.4
singularity run -B /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/ -B /mnt/NVMeScratch/tmp gcparagon_0.6.15-lenient.sif --bam /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/input_BAMs/20230530_ALL_B6_3_tf_0.01_cov_5.0.bam --temporary-directory /mnt/NVMeScratch/tmp --out-dir /media/benjamin/Analyses/GC_PARAGON_PUBLIC_TEST/GCparagon_output_v0.6.15/noBAM_output_moreSC-lenient_conda_env --preset 1 --threads 24 --dont-output-bam --unclipped-min-aln-fraction 0.4
